// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxycazoyoxrpbpgoxgod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4eWNhem95b3hycGJwZ294Z29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjMzMTQsImV4cCI6MjA3MTQzOTMxNH0.ZL8vX-yef3UME3iaVl7vMgpZXZQVaWDXy0YElSMGCZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});